### ISSUE TITLE
The "role"s of phantom parameters

### ISSUE THREAD

**Issue by enobayram** [matt-noonan/justified-containers#8]
Am I wrong in thinking that `ph` [in `Map`](https://github.com/matt-noonan/justified-containers/blob/cbc9e2529c6fc3f2b7a0886e7e985484933d4052/src/Data/Map/Justified.hs#L228), [`Key`](https://github.com/matt-noonan/justified-containers/blob/cbc9e2529c6fc3f2b7a0886e7e985484933d4052/src/Data/Map/Justified.hs#L237) and [`Index`](https://github.com/matt-noonan/justified-containers/blob/cbc9e2529c6fc3f2b7a0886e7e985484933d4052/src/Data/Map/Justified.hs#L246) should have the role `nominal`? As it is, we should be able to `coerce` a `Key` we obtained from one `Map` into a `Key` of a totally unrelated `Map`.

**Comment by matt-noonan** [comment]
Yikes, you are correct! For example, this definition currently compiles in the `Tutorial` module, which does not have access to `Key`'s constructor:

```haskell
argh :: Key ph k -> Key ph' k
argh = coerce
```

Changing the phantom roles to nominal solves the problem. But now I realize that the `gdp` library is going to need a similar treatment!

**Comment by matt-noonan** [comment]
Resolved by 288fb1f.
